import Head from "next/head";
import styles from "@/styles/Home.module.css";
import { Header } from "@/components/Headers";
import { ReactNode } from "react";



const Layout = ({ children }: { children: ReactNode }) => {
  return (
    <>
    <Head>
     <title> Create Next App</title>
     <meta name="descritpion" content="Generated by create next app" />
     <meta name="viewport" content="width-device-width, initial-scale-1" />
     <link rel="icon" href="/favicon.ico" />
        </Head>
        <Header />
               <main className="main-content">{children}</main>
  
    </>
  );
}

export default Layout;